/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author lucas
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }
classeGetSet abc = new classeGetSet();   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblBemVindo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnFuncionario = new javax.swing.JButton();
        btnPedidoEstatiscas = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnClienteOnline = new javax.swing.JButton();
        btnTotem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnRestaurante = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnRestauranteEstatisticas = new javax.swing.JButton();
        btnIngredientes = new javax.swing.JButton();
        pnConteudo = new javax.swing.JPanel();
        btnPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(247, 176, 54));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        lblBemVindo.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblBemVindo.setText("SEJA BEM-VINDO ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(lblBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblBemVindo)
                .addContainerGap(46, Short.MAX_VALUE))
            .addComponent(lblLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 110));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btnFuncionario.setBackground(new java.awt.Color(204, 204, 204));
        btnFuncionario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnFuncionario.setForeground(new java.awt.Color(51, 51, 51));
        btnFuncionario.setText("FUNCIONARIO");
        btnFuncionario.setActionCommand("");
        btnFuncionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnFuncionario.setBorderPainted(false);
        btnFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFuncionarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFuncionarioMouseExited(evt);
            }
        });
        btnFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionarioActionPerformed(evt);
            }
        });

        btnPedidoEstatiscas.setBackground(new java.awt.Color(204, 204, 204));
        btnPedidoEstatiscas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPedidoEstatiscas.setForeground(new java.awt.Color(51, 51, 51));
        btnPedidoEstatiscas.setText("ESTATISTICAS");
        btnPedidoEstatiscas.setActionCommand("");
        btnPedidoEstatiscas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPedidoEstatiscas.setBorderPainted(false);
        btnPedidoEstatiscas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPedidoEstatiscasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPedidoEstatiscasMouseExited(evt);
            }
        });
        btnPedidoEstatiscas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoEstatiscasActionPerformed(evt);
            }
        });

        btnProduto.setBackground(new java.awt.Color(204, 204, 204));
        btnProduto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnProduto.setForeground(new java.awt.Color(51, 51, 51));
        btnProduto.setText("PRODUTO");
        btnProduto.setActionCommand("");
        btnProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnProduto.setBorderPainted(false);
        btnProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProdutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProdutoMouseExited(evt);
            }
        });
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(204, 204, 204));
        btnSair.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSair.setForeground(new java.awt.Color(51, 51, 51));
        btnSair.setText("SAIR");
        btnSair.setActionCommand("");
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSairMouseExited(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("AGENTE");

        btnClienteOnline.setBackground(new java.awt.Color(204, 204, 204));
        btnClienteOnline.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnClienteOnline.setForeground(new java.awt.Color(51, 51, 51));
        btnClienteOnline.setText("CLIENTE ONLINE");
        btnClienteOnline.setActionCommand("");
        btnClienteOnline.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClienteOnline.setBorderPainted(false);
        btnClienteOnline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClienteOnlineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClienteOnlineMouseExited(evt);
            }
        });
        btnClienteOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteOnlineActionPerformed(evt);
            }
        });

        btnTotem.setBackground(new java.awt.Color(204, 204, 204));
        btnTotem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnTotem.setForeground(new java.awt.Color(51, 51, 51));
        btnTotem.setText("TOTEM");
        btnTotem.setActionCommand("");
        btnTotem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTotem.setBorderPainted(false);
        btnTotem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTotemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTotemMouseExited(evt);
            }
        });
        btnTotem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotemActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("PEDIDO");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel11.setText("PRODUTO");

        btnRestaurante.setBackground(new java.awt.Color(204, 204, 204));
        btnRestaurante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRestaurante.setForeground(new java.awt.Color(51, 51, 51));
        btnRestaurante.setText("RESTAURANTE");
        btnRestaurante.setActionCommand("");
        btnRestaurante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRestaurante.setBorderPainted(false);
        btnRestaurante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRestauranteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRestauranteMouseExited(evt);
            }
        });
        btnRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestauranteActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel12.setText("RESTAURANTE");

        btnRestauranteEstatisticas.setBackground(new java.awt.Color(204, 204, 204));
        btnRestauranteEstatisticas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRestauranteEstatisticas.setForeground(new java.awt.Color(51, 51, 51));
        btnRestauranteEstatisticas.setText("ESTATISTICAS");
        btnRestauranteEstatisticas.setActionCommand("");
        btnRestauranteEstatisticas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRestauranteEstatisticas.setBorderPainted(false);
        btnRestauranteEstatisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRestauranteEstatisticasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRestauranteEstatisticasMouseExited(evt);
            }
        });
        btnRestauranteEstatisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestauranteEstatisticasActionPerformed(evt);
            }
        });

        btnIngredientes.setBackground(new java.awt.Color(204, 204, 204));
        btnIngredientes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnIngredientes.setForeground(new java.awt.Color(51, 51, 51));
        btnIngredientes.setText("INGREDIENTES");
        btnIngredientes.setActionCommand("");
        btnIngredientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnIngredientes.setBorderPainted(false);
        btnIngredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngredientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngredientesMouseExited(evt);
            }
        });
        btnIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngredientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPedidoEstatiscas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnClienteOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTotem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRestaurante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRestauranteEstatisticas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTotem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClienteOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPedidoEstatiscas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(btnProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRestauranteEstatisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 180, 580));

        pnConteudo.setBackground(new java.awt.Color(255, 255, 255));
        pnConteudo.setLayout(new java.awt.CardLayout());
        jPanel3.add(pnConteudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 810, 340));

        btnPedido.setBackground(new java.awt.Color(255, 255, 255));
        btnPedido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnPedido.setActionCommand("");
        btnPedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPedido.setBorderPainted(false);
        btnPedido.setEnabled(false);
        btnPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPedidoMouseExited(evt);
            }
        });
        btnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoActionPerformed(evt);
            }
        });
        jPanel3.add(btnPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 180, 39));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
           pnPedido painel = new pnPedido();
         pnConteudo.removeAll();
                pnConteudo.add(painel);
                pnConteudo.revalidate();
                pnConteudo.setVisible(true);
    }//GEN-LAST:event_btnPedidoActionPerformed

    private void btnPedidoEstatiscasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoEstatiscasActionPerformed
      pnPedidoEstatistica painel = new pnPedidoEstatistica();
         pnConteudo.removeAll();
                pnConteudo.add(painel);
                pnConteudo.revalidate();
                pnConteudo.setVisible(true);
    }//GEN-LAST:event_btnPedidoEstatiscasActionPerformed

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
         pnProduto painel = new pnProduto();
         pnConteudo.removeAll();
                pnConteudo.add(painel);
                pnConteudo.revalidate();
                pnConteudo.setVisible(true);
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnFuncionarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionarioMouseEntered
 btnFuncionario.setBackground(new java.awt.Color(247,176,54));
    }//GEN-LAST:event_btnFuncionarioMouseEntered

    private void btnFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionarioMouseExited
     btnFuncionario.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnFuncionarioMouseExited

    private void btnRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestauranteActionPerformed
       pnRestaurante painel = new pnRestaurante();
         pnConteudo.removeAll();
                pnConteudo.add(painel);
                pnConteudo.revalidate();
                pnConteudo.setVisible(true);
    }//GEN-LAST:event_btnRestauranteActionPerformed

    private void btnRestauranteEstatisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestauranteEstatisticasActionPerformed
        pnRestauranteEstatistica painel = new pnRestauranteEstatistica();
         pnConteudo.removeAll();
                pnConteudo.add(painel);
                pnConteudo.revalidate();
                pnConteudo.setVisible(true);
    }//GEN-LAST:event_btnRestauranteEstatisticasActionPerformed

    private void btnIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngredientesActionPerformed
        pnIngredientes painel = new pnIngredientes();
         pnConteudo.removeAll();
                pnConteudo.add(painel);
                pnConteudo.revalidate();
                pnConteudo.setVisible(true);
    }//GEN-LAST:event_btnIngredientesActionPerformed

    private void btnTotemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTotemMouseEntered
      btnTotem.setBackground(new java.awt.Color(247,176,54));
    }//GEN-LAST:event_btnTotemMouseEntered

    private void btnTotemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTotemMouseExited
        btnTotem.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnTotemMouseExited

    private void btnClienteOnlineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteOnlineMouseEntered
       btnClienteOnline.setBackground(new java.awt.Color(247,176,54));
    }//GEN-LAST:event_btnClienteOnlineMouseEntered

    private void btnClienteOnlineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteOnlineMouseExited
       btnClienteOnline.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnClienteOnlineMouseExited

    private void btnPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedidoMouseEntered
        btnPedido.setBackground(new java.awt.Color(247,176,54));
    }//GEN-LAST:event_btnPedidoMouseEntered

    private void btnPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedidoMouseExited
      btnPedido.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnPedidoMouseExited

    private void btnPedidoEstatiscasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedidoEstatiscasMouseEntered
        btnPedidoEstatiscas.setBackground(new java.awt.Color(247,176,54));
    }//GEN-LAST:event_btnPedidoEstatiscasMouseEntered

    private void btnPedidoEstatiscasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedidoEstatiscasMouseExited
     btnPedidoEstatiscas.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnPedidoEstatiscasMouseExited

    private void btnProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutoMouseEntered
         btnProduto.setBackground(new java.awt.Color(247,176,54));
    }//GEN-LAST:event_btnProdutoMouseEntered

    private void btnProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutoMouseExited
        btnProduto.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnProdutoMouseExited

    private void btnIngredientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngredientesMouseEntered
         btnIngredientes.setBackground(new java.awt.Color(247,176,54));
    }//GEN-LAST:event_btnIngredientesMouseEntered

    private void btnIngredientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngredientesMouseExited
      btnIngredientes.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnIngredientesMouseExited

    private void btnRestauranteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestauranteMouseEntered
         btnRestaurante.setBackground(new java.awt.Color(247,176,54));
    }//GEN-LAST:event_btnRestauranteMouseEntered

    private void btnRestauranteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestauranteMouseExited
        btnRestaurante.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnRestauranteMouseExited

    private void btnRestauranteEstatisticasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestauranteEstatisticasMouseEntered
         btnRestauranteEstatisticas.setBackground(new java.awt.Color(247,176,54));
    }//GEN-LAST:event_btnRestauranteEstatisticasMouseEntered

    private void btnRestauranteEstatisticasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestauranteEstatisticasMouseExited
      btnRestauranteEstatisticas.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnRestauranteEstatisticasMouseExited

    private void btnSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseEntered
         btnSair.setBackground(new java.awt.Color(255,51,51));
    }//GEN-LAST:event_btnSairMouseEntered

    private void btnSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseExited
     btnSair.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnSairMouseExited

    private void btnFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionarioActionPerformed
       pnMenufunc painel = new pnMenufunc();
         pnConteudo.removeAll();
                pnConteudo.add(painel);
                pnConteudo.revalidate();
                pnConteudo.setVisible(true);
    }//GEN-LAST:event_btnFuncionarioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
        ImageIcon imagem;
        imagem = new ImageIcon(getClass().getResource("sblenderGrande.jpeg"));
       lblLogin.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(lblLogin.getWidth(), lblLogin.getHeight(), Image.SCALE_DEFAULT)));
        
        
        
        lblBemVindo.setText(lblBemVindo.getText()+classeGetSet.getNome().toUpperCase());
    }//GEN-LAST:event_formWindowOpened

    private void btnTotemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotemActionPerformed
        
         pnMenuTotem painel = new pnMenuTotem();
         pnConteudo.removeAll();
                pnConteudo.add(painel);
                pnConteudo.revalidate();
                pnConteudo.setVisible(true);
        
        
    }//GEN-LAST:event_btnTotemActionPerformed

    private void btnClienteOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteOnlineActionPerformed
         pnMenuClienteOnline painel = new pnMenuClienteOnline();
         pnConteudo.removeAll();
                pnConteudo.add(painel);
                pnConteudo.revalidate();
                pnConteudo.setVisible(true);
    }//GEN-LAST:event_btnClienteOnlineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienteOnline;
    private javax.swing.JButton btnFuncionario;
    private javax.swing.JButton btnIngredientes;
    private javax.swing.JButton btnPedido;
    private javax.swing.JButton btnPedidoEstatiscas;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnRestaurante;
    private javax.swing.JButton btnRestauranteEstatisticas;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTotem;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JPanel pnConteudo;
    // End of variables declaration//GEN-END:variables
}
